# === Data preprocessing ===
observed_functional_data_path: Computation_templates/Example_data.RData
rec_basis_type: fourier 
time_range: [0, 1] 
time_points: 100
rec_basis_number: 15 


# === Input and Output Paths ===
input_path: Computation_templates/Example_data_score.RData
output_path: Computation_templates/results/
name_output: example
n_nodes: 10
n_basis_for_dim_reduction: 5  # number of fPC to retain

# === Model Parameters ===
L: 100
K: 5
thres_ctrl: [0, 0.2, 0.4, 0.8, 1.2, 1.6, 2.0]
p_rand_lam: 0.5
p_rand_thr: 1

# === Symmetrization Parameters ===
type: OR

# === General Parameters ===
verbose: TRUE
